# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b02b7ad845b8ce4bfc23abe011066e319fecd7f4d078653dc22de605c1aa6178bb9d03300b81365f24aa8f75bf800b2860ef2ed5db8fe9948029108540f37702

test:
  secret_key_base: e5e865570bc78d5055f39a9f7ab41118f476940e860b81526a9e9ff8b4ca49f038ceb06f9acdbea1f651ccd99b275f5e4e3ea8ae1c41a7087eaa23435e41aa89

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
